name: hoteldetail_dart
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dio: ^4.0.6
  objectbox: ^1.7.2
  string_similarity: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  objectbox_generator: any
  test: ^1.19.2
  very_good_analysis: ^3.1.0
